依存関係の修正
approvers/site pull request #203
Opened 2021-05-22 09:22 UTC by MikuroXina

- セキュリティアラートの修正をしたはずが, peer dependency 周りが直っていなかったので修正
- husky のセットアップが間違っていたようなので修正

2021-05-22 09:29 UTC, shun-shobon requested changes

2021-05-22 09:29 UTC, shun-shobon commented on .gitignore
> +.husky
こうする必要な無いはずです。`.husky`はコミットするべきディレクトリです。

2021-05-22 09:29 UTC, shun-shobon commented on package.json
>    "husky": {
huskyは`package.json`での設定が廃止されたため、削除して構いません。

2021-05-22 09:41 UTC, MikuroXina commented on package.json
>    "husky": {
916df79 で対応しました.

2021-05-22 09:41 UTC, MikuroXina commented on .gitignore
> +.husky
dddee14 と 3c44926 で修正しました.

2021-05-22 17:04 UTC, shun-shobon requested changes

2021-05-22 17:04 UTC, shun-shobon commented on .husky/pre-commit
> +npx lint-staged
yarnでいいんじゃないですかね
```suggestion
yarn lint-staged
```

2021-05-22 17:11 UTC, shun-shobon approved these changes

2021-05-23 06:53 UTC, siketyan approved these changes

2021-05-23 06:53 UTC, merged