ダークテーマの追加
approvers/site pull request #246
Opened 2022-02-27 16:55 UTC by MikuroXina

2022-03-01 09:55 UTC, shun-shobon submitted a review, later dismissed
LGTM

2022-03-01 12:49 UTC, shun-shobon approved these changes

2022-03-01 12:49 UTC, shun-shobon approved these changes

2022-03-03 03:42 UTC, YukiYuigishi commented
LGTM

2022-03-03 16:42 UTC, merunno requested changes
> 至らない点もあるので謝ったレビューがあれば解決済みでのマークをお願いします.... 🙇‍♀️

2022-03-03 16:42 UTC, merunno commented on src/components/prev-next-link.tsx
> +  <Flex as="nav" color="highlighted" mt={4} mb={4}>
ここも型を統一で

2022-03-03 16:42 UTC, merunno commented on src/pages/blog.tsx
> +  <HStack borderBottom="2px" borderRight="1px" borderColor="shadowed">
ここも

2022-03-03 16:42 UTC, merunno commented on src/pages/index.tsx
> +      <Heading as="h1" fontSize="5xl" pt={32} pb={2} textAlign="center" zIndex={10}>
ここも同様

2022-03-03 16:59 UTC, shun-shobon approved these changes

2022-03-03 16:59 UTC, merged