test: jest から vitest への移行
approvers/site pull request #255
Opened 2022-07-20 14:11 UTC by MikuroXina

2022-07-31 23:47 UTC, mirror-kt submitted a review, later dismissed
ちゃんとテスト通ってるならヨシ(適当approve)

2022-11-04 09:00 UTC, shun-shobon approved these changes

2022-11-04 16:22 UTC, shun-shobon approved these changes

2022-11-04 16:38 UTC, shun-shobon commented
純粋に気になるんですけどreact testing libraryからreact test rendererに移行した理由はありますか？

2022-11-04 17:02 UTC, MikuroXina commented
@shun-shobon Vitest でスナップショットテストを行うサンプルが React Test Renderer を使用していたのでそれに合わせただけです. 差し戻すべきですか?

2022-11-05 01:20 UTC, shun-shobon commented
@MikuroXina とりあえず現状のテストの使い方なら大きな問題は無いと思いますので差し戻しは不要だと思います。ありがとうございます。

2022-11-05 01:21 UTC, shun-shobon requested changes
一点だけ
(なんかよく見ると色々不要なものが混じってるのでそのうち消したいですね)

2022-11-05 01:25 UTC, MikuroXina commented on package.json
>      "identity-obj-proxy": "^3.0.0",
20cb2fc で修正しました. そもそも Jest の config を消し忘れてました

2022-11-05 01:26 UTC, shun-shobon approved these changes
LGTM 👍 
長い間放置してすみませんでした

2022-11-05 01:27 UTC, merged